Importing the Libraries

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.metrics import confusion_matrix, accuracy_score

Importing the Dataset

In [ ]:
dataset = pd.read_csv('Copy of sonar data.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

Splitting the dataset into the Training set and Test set

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

In [ ]:
print(X_train)

[[0.0231 0.0315 0.017  ... 0.0091 0.0008 0.0092]
 [0.0272 0.0378 0.0488 ... 0.0051 0.0065 0.0103]
 [0.0164 0.0173 0.0347 ... 0.0035 0.0056 0.004 ]
 ...
 [0.0363 0.0478 0.0298 ... 0.0114 0.0073 0.0033]
 [0.019  0.0038 0.0642 ... 0.0022 0.0055 0.0122]
 [0.0329 0.0216 0.0386 ... 0.0042 0.0053 0.0074]]


In [ ]:
print(y_train)

['M' 'M' 'R' 'R' 'M' 'M' 'M' 'M' 'M' 'M' 'R' 'R' 'R' 'R' 'R' 'R' 'M' 'R'
 'R' 'M' 'M' 'R' 'M' 'R' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'R' 'R' 'M' 'M'
 'R' 'R' 'M' 'M' 'M' 'R' 'R' 'R' 'M' 'M' 'R' 'R' 'M' 'R' 'M' 'M' 'M' 'M'
 'M' 'R' 'R' 'M' 'M' 'M' 'R' 'M' 'R' 'R' 'M' 'R' 'R' 'M' 'R' 'R' 'R' 'R'
 'R' 'M' 'R' 'M' 'R' 'R' 'M' 'M' 'M' 'R' 'R' 'R' 'M' 'M' 'M' 'M' 'R' 'M'
 'R' 'M' 'M' 'R' 'R' 'R' 'R' 'M' 'M' 'R' 'M' 'M' 'M' 'R' 'R' 'M' 'R' 'M'
 'M' 'R' 'R' 'M' 'M' 'M' 'R' 'M' 'M' 'M' 'R' 'M' 'M' 'M' 'M' 'R' 'M' 'R'
 'M' 'R' 'M' 'M' 'M' 'R' 'R' 'R' 'M' 'R' 'M' 'M' 'M' 'R' 'R' 'M' 'R' 'R'
 'R' 'R' 'R' 'R' 'M' 'M' 'R' 'M' 'M' 'R' 'M']


In [ ]:
print(X_test)

[[0.009  0.0062 0.0253 ... 0.0053 0.0189 0.0102]
 [0.01   0.0194 0.0155 ... 0.0019 0.0053 0.0019]
 [0.0311 0.0491 0.0692 ... 0.0182 0.0046 0.0038]
 ...
 [0.0264 0.0071 0.0342 ... 0.0077 0.0078 0.0066]
 [0.0177 0.03   0.0288 ... 0.0057 0.0032 0.0019]
 [0.0587 0.121  0.1268 ... 0.0101 0.0228 0.0124]]


In [ ]:
print(y_test)

['R' 'R' 'R' 'R' 'M' 'R' 'M' 'M' 'R' 'M' 'R' 'M' 'R' 'M' 'M' 'R' 'M' 'R'
 'R' 'R' 'M' 'R' 'R' 'R' 'R' 'M' 'M' 'M' 'M' 'M' 'R' 'M' 'M' 'R' 'M' 'M'
 'M' 'M' 'R' 'M' 'M' 'R' 'M' 'M' 'R' 'R' 'M' 'R' 'R' 'M' 'R' 'M']


Feature Scaling

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [ ]:
print(X_train)

[[-0.24455667 -0.19282221 -0.66444099 ...  0.19440093 -1.20244692
   0.60902323]
 [-0.06348273  0.00436167  0.13849851 ... -0.44739128 -0.22050603
   0.85491113]
 [-0.540458   -0.63726842 -0.21752183 ... -0.70410817 -0.37554933
  -0.55335594]
 ...
 [ 0.3384131   0.31735196 -0.34124522 ...  0.56343146 -0.08268976
  -0.70983006]
 [-0.42563062 -1.05980531  0.52734343 ... -0.91269064 -0.39277636
   1.27962659]
 [ 0.18825422 -0.5026826  -0.11904812 ... -0.59179453 -0.42723043
   0.20666121]]


In [ ]:
print(X_test)

[[-0.86727438 -0.98468764 -0.45486873 ... -0.41530167  1.9156461
   0.83255768]
 [-0.82311001 -0.57154046 -0.7023155  ... -0.96082505 -0.42723043
  -1.02277829]
 [ 0.10875834  0.3580407   0.65359178 ...  1.65447822 -0.54781966
  -0.59806283]
 ...
 [-0.09881423 -0.95651852 -0.23014667 ... -0.03022634  0.00344541
   0.02783365]
 [-0.48304431 -0.23977075 -0.36649489 ... -0.35112245 -0.78899812
  -1.02277829]
 [ 1.32769513  2.60844088  2.10797277 ...  0.35484899  2.5875004
   1.32433348]]


Training the Logistic Regression model on the Training set

In [ ]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(X_train, y_train)

LogisticRegression(random_state=0)

Predicting the Test set results

In [ ]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[['R' 'R']
 ['M' 'R']
 ['R' 'R']
 ['R' 'R']
 ['R' 'M']
 ['M' 'R']
 ['M' 'M']
 ['M' 'M']
 ['R' 'R']
 ['M' 'M']
 ['M' 'R']
 ['M' 'M']
 ['R' 'R']
 ['M' 'M']
 ['R' 'M']
 ['R' 'R']
 ['M' 'M']
 ['R' 'R']
 ['R' 'R']
 ['M' 'R']
 ['M' 'M']
 ['R' 'R']
 ['M' 'R']
 ['M' 'R']
 ['M' 'R']
 ['M' 'M']
 ['M' 'M']
 ['M' 'M']
 ['M' 'M']
 ['M' 'M']
 ['R' 'R']
 ['M' 'M']
 ['M' 'M']
 ['R' 'R']
 ['M' 'M']
 ['M' 'M']
 ['M' 'M']
 ['M' 'M']
 ['M' 'R']
 ['M' 'M']
 ['M' 'M']
 ['R' 'R']
 ['M' 'M']
 ['M' 'M']
 ['R' 'R']
 ['M' 'R']
 ['M' 'M']
 ['M' 'R']
 ['R' 'R']
 ['M' 'M']
 ['R' 'R']
 ['M' 'M']]


Making the Confusion Matrix

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[25  2]
 [10 15]]


0.7692307692307693

Making a Predictive System

In [ ]:
print(classifier.predict(sc.transform([[0.0307,0.0523,0.0653,0.0521,0.0611,0.0577,0.0665,0.0664,0.1460,0.2792,0.3877,0.4992,0.4981,0.4972,0.5607,0.7339,0.8230,0.9173,0.9975,0.9911,0.8240,0.6498,0.5980,0.4862,0.3150,0.1543,0.0989,0.0284,0.1008,0.2636,0.2694,0.2930,0.2925,0.3998,0.3660,0.3172,0.4609,0.4374,0.1820,0.3376,0.6202,0.4448,0.1863,0.1420,0.0589,0.0576,0.0672,0.0269,0.0245,0.0190,0.0063,0.0321,0.0189,0.0137,0.0277,0.0152,0.0052,0.0121,0.0124,0.0055]])))

['M']
